/*
 * This file is generated by jOOQ.
 */
package de.tichawa.cis.config.model.tables;


import de.tichawa.cis.config.model.*;
import de.tichawa.cis.config.model.tables.records.MechanicRecord;
import org.jooq.*;
import org.jooq.impl.*;

import java.util.*;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Mechanic extends TableImpl<MechanicRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mechanic</code>
     */
    public static final Mechanic MECHANIC = new Mechanic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MechanicRecord> getRecordType() {
        return MechanicRecord.class;
    }

    /**
     * The column <code>mechanic.cis_type</code>.
     */
    public final TableField<MechanicRecord, String> CIS_TYPE = createField(DSL.name("cis_type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>mechanic.cis_length</code>.
     */
    public final TableField<MechanicRecord, Integer> CIS_LENGTH = createField(DSL.name("cis_length"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mechanic.coax_lights</code>.
     */
    public final TableField<MechanicRecord, String> LIGHTS = createField(DSL.name("lights"), SQLDataType.VARCHAR.nullable(true), this, "");

    /**
     * The column <code>mechanic.select_code</code>.
     */
    public final TableField<MechanicRecord, String> SELECT_CODE = createField(DSL.name("select_code"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>mechanic.art_no</code>.
     */
    public final TableField<MechanicRecord, Integer> ART_NO = createField(DSL.name("art_no"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mechanic.amount</code>.
     */
    public final TableField<MechanicRecord, String> AMOUNT = createField(DSL.name("amount"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>mechanic.art_no</code>.
     */
    public final TableField<MechanicRecord, Integer> NEXT_SIZE_ART_NO = createField(DSL.name("next_size_art_no"), SQLDataType.INTEGER.nullable(true), this, "");

    private Mechanic(Name alias, Table<MechanicRecord> aliased) {
        this(alias, aliased, null);
    }

    private Mechanic(Name alias, Table<MechanicRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>mechanic</code> table reference
     */
    public Mechanic(String alias) {
        this(DSL.name(alias), MECHANIC);
    }

    /**
     * Create an aliased <code>mechanic</code> table reference
     */
    public Mechanic(Name alias) {
        this(alias, MECHANIC);
    }

    /**
     * Create a <code>mechanic</code> table reference
     */
    public Mechanic() {
        this(DSL.name("mechanic"), null);
    }

    public <O extends Record> Mechanic(Table<O> child, ForeignKey<O, MechanicRecord> key) {
        super(child, key, MECHANIC);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<ForeignKey<MechanicRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MechanicRecord, ?>>asList(Keys.FK_MECHANIC_PRICE_1, Keys.FK_MECHANIC_PRICE_2);
    }

    private transient Price _price;

    public Price price() {
        if (_price == null)
            _price = new Price(this, Keys.FK_MECHANIC_PRICE_1);

        return _price;
    }

    @Override
    public Mechanic as(String alias) {
        return new Mechanic(DSL.name(alias), this);
    }

    @Override
    public Mechanic as(Name alias) {
        return new Mechanic(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Mechanic rename(String name) {
        return new Mechanic(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Mechanic rename(Name name) {
        return new Mechanic(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, Integer, String, String, Integer, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
