/*
 * This file is generated by jOOQ.
 */
package de.tichawa.cis.config.model.tables.records;


import de.tichawa.cis.config.model.tables.AdcBoard;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdcBoardRecord extends UpdatableRecordImpl<AdcBoardRecord> implements Record4<String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tivicc.adc_board.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tivicc.adc_board.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tivicc.adc_board.adcs</code>.
     */
    public void setAdcs(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>tivicc.adc_board.adcs</code>.
     */
    public Integer getAdcs() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>tivicc.adc_board.channels</code>.
     */
    public void setChannels(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>tivicc.adc_board.channels</code>.
     */
    public Integer getChannels() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>tivicc.adc_board.clock_speed</code>.
     */
    public void setClockSpeed(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>tivicc.adc_board.clock_speed</code>.
     */
    public Integer getClockSpeed() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AdcBoard.ADC_BOARD.NAME;
    }

    @Override
    public Field<Integer> field2() {
        return AdcBoard.ADC_BOARD.ADCS;
    }

    @Override
    public Field<Integer> field3() {
        return AdcBoard.ADC_BOARD.CHANNELS;
    }

    @Override
    public Field<Integer> field4() {
        return AdcBoard.ADC_BOARD.CLOCK_SPEED;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public Integer component2() {
        return getAdcs();
    }

    @Override
    public Integer component3() {
        return getChannels();
    }

    @Override
    public Integer component4() {
        return getClockSpeed();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public Integer value2() {
        return getAdcs();
    }

    @Override
    public Integer value3() {
        return getChannels();
    }

    @Override
    public Integer value4() {
        return getClockSpeed();
    }

    @Override
    public AdcBoardRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public AdcBoardRecord value2(Integer value) {
        setAdcs(value);
        return this;
    }

    @Override
    public AdcBoardRecord value3(Integer value) {
        setChannels(value);
        return this;
    }

    @Override
    public AdcBoardRecord value4(Integer value) {
        setClockSpeed(value);
        return this;
    }

    @Override
    public AdcBoardRecord values(String value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdcBoardRecord
     */
    public AdcBoardRecord() {
        super(AdcBoard.ADC_BOARD);
    }

    /**
     * Create a detached, initialised AdcBoardRecord
     */
    public AdcBoardRecord(String name, Integer adcs, Integer channels, Integer clockSpeed) {
        super(AdcBoard.ADC_BOARD);

        setName(name);
        setAdcs(adcs);
        setChannels(channels);
        setClockSpeed(clockSpeed);
    }
}
