/*
 * This file is generated by jOOQ.
 */
package de.tichawa.cis.config.model.tables.records;


import de.tichawa.cis.config.model.tables.Equipment;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EquipmentRecord extends UpdatableRecordImpl<EquipmentRecord> implements Record5<Integer, Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>equipment.art_no_ferix_old</code>.
     */
    public void setArtNoFerixOld(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>equipment.art_no_ferix_old</code>.
     */
    public Integer getArtNoFerixOld() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>equipment.art_no_ferix_new</code>.
     */
    public void setArtNoFerixNew(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>equipment.art_no_ferix_new</code>.
     */
    public Integer getArtNoFerixNew() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>equipment.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>equipment.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>equipment.select_code</code>.
     */
    public void setSelectCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>equipment.select_code</code>.
     */
    public String getSelectCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>equipment.amount</code>.
     */
    public void setAmount(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>equipment.amount</code>.
     */
    public String getAmount() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Equipment.EQUIPMENT.ART_NO_FERIX_OLD;
    }

    @Override
    public Field<Integer> field2() {
        return Equipment.EQUIPMENT.ART_NO_FERIX_NEW;
    }

    @Override
    public Field<String> field3() {
        return Equipment.EQUIPMENT.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Equipment.EQUIPMENT.SELECT_CODE;
    }

    @Override
    public Field<String> field5() {
        return Equipment.EQUIPMENT.AMOUNT;
    }

    @Override
    public Integer component1() {
        return getArtNoFerixOld();
    }

    @Override
    public Integer component2() {
        return getArtNoFerixNew();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getSelectCode();
    }

    @Override
    public String component5() {
        return getAmount();
    }

    @Override
    public Integer value1() {
        return getArtNoFerixOld();
    }

    @Override
    public Integer value2() {
        return getArtNoFerixNew();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getSelectCode();
    }

    @Override
    public String value5() {
        return getAmount();
    }

    @Override
    public EquipmentRecord value1(Integer value) {
        setArtNoFerixOld(value);
        return this;
    }

    @Override
    public EquipmentRecord value2(Integer value) {
        setArtNoFerixNew(value);
        return this;
    }

    @Override
    public EquipmentRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public EquipmentRecord value4(String value) {
        setSelectCode(value);
        return this;
    }

    @Override
    public EquipmentRecord value5(String value) {
        setAmount(value);
        return this;
    }

    @Override
    public EquipmentRecord values(Integer value1, Integer value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EquipmentRecord
     */
    public EquipmentRecord() {
        super(Equipment.EQUIPMENT);
    }

    /**
     * Create a detached, initialised EquipmentRecord
     */
    public EquipmentRecord(Integer artNoFerixOld, Integer artNoFerixNew, String description, String selectCode, String amount) {
        super(Equipment.EQUIPMENT);

        setArtNoFerixOld(artNoFerixOld);
        setArtNoFerixNew(artNoFerixNew);
        setDescription(description);
        setSelectCode(selectCode);
        setAmount(amount);
    }
}
