/*
 * This file is generated by jOOQ.
 */
package de.tichawa.cis.config.model.tables.records;


import de.tichawa.cis.config.model.tables.*;
import org.jooq.*;
import org.jooq.impl.*;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EquipmentRecord extends UpdatableRecordImpl<EquipmentRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tivicc.price.art_no</code>.
     */
    public void setArtNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tivicc.price.art_no</code>.
     */
    public Integer getArtNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tivicc.price.ferix_key</code>.
     */
    public void setSelectCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tivicc.price.ferix_key</code>.
     */
    public String getSelectCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tivicc.price.display_name</code>.
     */
    public void setAmount(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tivicc.price.display_name</code>.
     */
    public String getAmount() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Equipment.EQUIPMENT.ART_NO;
    }

    @Override
    public Field<String> field2() {
        return Equipment.EQUIPMENT.SELECT_CODE;
    }

    @Override
    public Field<String> field3() {
        return Equipment.EQUIPMENT.AMOUNT;
    }

    @Override
    public Integer component1() {
        return getArtNo();
    }

    @Override
    public String component2() {
        return getSelectCode();
    }

    @Override
    public String component3() {
        return getAmount();
    }

    @Override
    public Integer value1() {
        return getArtNo();
    }

    @Override
    public String value2() {
        return getSelectCode();
    }

    @Override
    public String value3() {
        return getAmount();
    }

    @Override
    public EquipmentRecord value1(Integer value) {
        setArtNo(value);
        return this;
    }

    @Override
    public EquipmentRecord value2(String value) {
        setSelectCode(value);
        return this;
    }

    @Override
    public EquipmentRecord value3(String value) {
        setAmount(value);
        return this;
    }

    @Override
    public EquipmentRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PriceRecord
     */
    public EquipmentRecord() {
        super(Equipment.EQUIPMENT);
    }

    /**
     * Create a detached, initialised PriceRecord
     */
    public EquipmentRecord(Integer artNo, String selectCode, String amount) {
        super(Equipment.EQUIPMENT);

        setArtNo(artNo);
        setSelectCode(selectCode);
        setAmount(amount);
    }
}
