/*
 * This file is generated by jOOQ.
 */
package de.tichawa.cis.config.model.tables.records;


import de.tichawa.cis.config.model.tables.Mechanic;

import org.jooq.*;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MechanicRecord extends TableRecordImpl<MechanicRecord> implements Record6<String, Integer, String, String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mechanic.cis_type</code>.
     */
    public void setCisType(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mechanic.cis_type</code>.
     */
    public String getCisType() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mechanic.cis_length</code>.
     */
    public void setCisLength(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mechanic.cis_length</code>.
     */
    public Integer getCisLength() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mechanic.diffuse_lights</code>.
     */
    public void setLights(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mechanic.diffuse_lights</code>.
     */
    public String getLights() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mechanic.select_code</code>.
     */
    public void setSelectCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mechanic.select_code</code>.
     */
    public String getSelectCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mechanic.art_no</code>.
     */
    public void setArtNo(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>mechanic.art_no</code>.
     */
    public Integer getArtNo() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>mechanic.amount</code>.
     */
    public void setAmount(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mechanic.amount</code>.
     */
    public String getAmount() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, Integer, String, String, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, Integer, String, String, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Mechanic.MECHANIC.CIS_TYPE;
    }

    @Override
    public Field<Integer> field2() {
        return Mechanic.MECHANIC.CIS_LENGTH;
    }

    @Override
    public Field<String> field3() {
        return Mechanic.MECHANIC.LIGHTS;
    }

    @Override
    public Field<String> field4() {
        return Mechanic.MECHANIC.SELECT_CODE;
    }

    @Override
    public Field<Integer> field5() {
        return Mechanic.MECHANIC.ART_NO;
    }

    @Override
    public Field<String> field6() {
        return Mechanic.MECHANIC.AMOUNT;
    }

    @Override
    public String component1() {
        return getCisType();
    }

    @Override
    public Integer component2() {
        return getCisLength();
    }

    @Override
    public String component3() {
        return getLights();
    }

    @Override
    public String component4() {
        return getSelectCode();
    }

    @Override
    public Integer component5() {
        return getArtNo();
    }

    @Override
    public String component6() {
        return getAmount();
    }

    @Override
    public String value1() {
        return getCisType();
    }

    @Override
    public Integer value2() {
        return getCisLength();
    }

    @Override
    public String value3() {
        return getLights();
    }

    @Override
    public String value4() {
        return getSelectCode();
    }

    @Override
    public Integer value5() {
        return getArtNo();
    }

    @Override
    public String value6() {
        return getAmount();
    }

    @Override
    public MechanicRecord value1(String value) {
        setCisType(value);
        return this;
    }

    @Override
    public MechanicRecord value2(Integer value) {
        setCisLength(value);
        return this;
    }

    @Override
    public MechanicRecord value3(String value) {
        setLights(value);
        return this;
    }

    @Override
    public MechanicRecord value4(String value) {
        setSelectCode(value);
        return this;
    }

    @Override
    public MechanicRecord value5(Integer value) {
        setArtNo(value);
        return this;
    }

    @Override
    public MechanicRecord value6(String value) {
        setAmount(value);
        return this;
    }

    @Override
    public MechanicRecord values(String value1, Integer value2, String value3, String value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MechanicRecord
     */
    public MechanicRecord() {
        super(Mechanic.MECHANIC);
    }

    /**
     * Create a detached, initialised MechanicRecord
     */
    public MechanicRecord(String cisType, Integer cisLength, String lights, String selectCode, Integer artNo, String amount) {
        super(Mechanic.MECHANIC);

        setCisType(cisType);
        setCisLength(cisLength);
        setLights(lights);
        setSelectCode(selectCode);
        setArtNo(artNo);
        setAmount(amount);
    }
}
