/*
 * This file is generated by jOOQ.
 */
package de.tichawa.cis.config.model.tables.records;


import de.tichawa.cis.config.model.tables.Mechanic;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MechanicRecord extends TableRecordImpl<MechanicRecord> implements Record7<String, Integer, Integer, Integer, String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tivicc.mechanic.cis_type</code>.
     */
    public void setCisType(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tivicc.mechanic.cis_type</code>.
     */
    public String getCisType() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tivicc.mechanic.cis_length</code>.
     */
    public void setCisLength(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>tivicc.mechanic.cis_length</code>.
     */
    public Integer getCisLength() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>tivicc.mechanic.diffuse_lights</code>.
     */
    public void setDiffuseLights(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>tivicc.mechanic.diffuse_lights</code>.
     */
    public Integer getDiffuseLights() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>tivicc.mechanic.coax_lights</code>.
     */
    public void setCoaxLights(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>tivicc.mechanic.coax_lights</code>.
     */
    public Integer getCoaxLights() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>tivicc.mechanic.select_code</code>.
     */
    public void setSelectCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tivicc.mechanic.select_code</code>.
     */
    public String getSelectCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tivicc.mechanic.art_no</code>.
     */
    public void setArtNo(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>tivicc.mechanic.art_no</code>.
     */
    public Integer getArtNo() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>tivicc.mechanic.amount</code>.
     */
    public void setAmount(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>tivicc.mechanic.amount</code>.
     */
    public String getAmount() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, Integer, Integer, Integer, String, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, Integer, Integer, Integer, String, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Mechanic.MECHANIC.CIS_TYPE;
    }

    @Override
    public Field<Integer> field2() {
        return Mechanic.MECHANIC.CIS_LENGTH;
    }

    @Override
    public Field<Integer> field3() {
        return Mechanic.MECHANIC.DIFFUSE_LIGHTS;
    }

    @Override
    public Field<Integer> field4() {
        return Mechanic.MECHANIC.COAX_LIGHTS;
    }

    @Override
    public Field<String> field5() {
        return Mechanic.MECHANIC.SELECT_CODE;
    }

    @Override
    public Field<Integer> field6() {
        return Mechanic.MECHANIC.ART_NO;
    }

    @Override
    public Field<String> field7() {
        return Mechanic.MECHANIC.AMOUNT;
    }

    @Override
    public String component1() {
        return getCisType();
    }

    @Override
    public Integer component2() {
        return getCisLength();
    }

    @Override
    public Integer component3() {
        return getDiffuseLights();
    }

    @Override
    public Integer component4() {
        return getCoaxLights();
    }

    @Override
    public String component5() {
        return getSelectCode();
    }

    @Override
    public Integer component6() {
        return getArtNo();
    }

    @Override
    public String component7() {
        return getAmount();
    }

    @Override
    public String value1() {
        return getCisType();
    }

    @Override
    public Integer value2() {
        return getCisLength();
    }

    @Override
    public Integer value3() {
        return getDiffuseLights();
    }

    @Override
    public Integer value4() {
        return getCoaxLights();
    }

    @Override
    public String value5() {
        return getSelectCode();
    }

    @Override
    public Integer value6() {
        return getArtNo();
    }

    @Override
    public String value7() {
        return getAmount();
    }

    @Override
    public MechanicRecord value1(String value) {
        setCisType(value);
        return this;
    }

    @Override
    public MechanicRecord value2(Integer value) {
        setCisLength(value);
        return this;
    }

    @Override
    public MechanicRecord value3(Integer value) {
        setDiffuseLights(value);
        return this;
    }

    @Override
    public MechanicRecord value4(Integer value) {
        setCoaxLights(value);
        return this;
    }

    @Override
    public MechanicRecord value5(String value) {
        setSelectCode(value);
        return this;
    }

    @Override
    public MechanicRecord value6(Integer value) {
        setArtNo(value);
        return this;
    }

    @Override
    public MechanicRecord value7(String value) {
        setAmount(value);
        return this;
    }

    @Override
    public MechanicRecord values(String value1, Integer value2, Integer value3, Integer value4, String value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MechanicRecord
     */
    public MechanicRecord() {
        super(Mechanic.MECHANIC);
    }

    /**
     * Create a detached, initialised MechanicRecord
     */
    public MechanicRecord(String cisType, Integer cisLength, Integer diffuseLights, Integer coaxLights, String selectCode, Integer artNo, String amount) {
        super(Mechanic.MECHANIC);

        setCisType(cisType);
        setCisLength(cisLength);
        setDiffuseLights(diffuseLights);
        setCoaxLights(coaxLights);
        setSelectCode(selectCode);
        setArtNo(artNo);
        setAmount(amount);
    }
}
