/*
 * This file is generated by jOOQ.
 */
package de.tichawa.cis.config.model;


import de.tichawa.cis.config.model.tables.AdcBoard;
import de.tichawa.cis.config.model.tables.Config;
import de.tichawa.cis.config.model.tables.Electronic;
import de.tichawa.cis.config.model.tables.Equipment;
import de.tichawa.cis.config.model.tables.Mechanic;
import de.tichawa.cis.config.model.tables.Price;
import de.tichawa.cis.config.model.tables.SensorBoard;
import de.tichawa.cis.config.model.tables.SensorChip;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>adc_board</code>.
     */
    public final AdcBoard ADC_BOARD = AdcBoard.ADC_BOARD;

    /**
     * The table <code>config</code>.
     */
    public final Config CONFIG = Config.CONFIG;

    /**
     * The table <code>electronic</code>.
     */
    public final Electronic ELECTRONIC = Electronic.ELECTRONIC;

    /**
     * The table <code>equipment</code>.
     */
    public final Equipment EQUIPMENT = Equipment.EQUIPMENT;

    /**
     * The table <code>mechanic</code>.
     */
    public final Mechanic MECHANIC = Mechanic.MECHANIC;

    /**
     * The table <code>price</code>.
     */
    public final Price PRICE = Price.PRICE;

    /**
     * The table <code>sensor_board</code>.
     */
    public final SensorBoard SENSOR_BOARD = SensorBoard.SENSOR_BOARD;

    /**
     * The table <code>sensor_chip</code>.
     */
    public final SensorChip SENSOR_CHIP = SensorChip.SENSOR_CHIP;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            AdcBoard.ADC_BOARD,
            Config.CONFIG,
            Electronic.ELECTRONIC,
            Equipment.EQUIPMENT,
            Mechanic.MECHANIC,
            Price.PRICE,
            SensorBoard.SENSOR_BOARD,
            SensorChip.SENSOR_CHIP);
    }
}
