/*
 * This file is generated by jOOQ.
 */
package de.tichawa.cis.config.model;


import de.tichawa.cis.config.model.tables.Electronic;
import de.tichawa.cis.config.model.tables.Mechanic;
import de.tichawa.cis.config.model.tables.Price;


/**
 * Convenience access to all tables in tivicc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tivicc.electronic</code>.
     */
    public static final Electronic ELECTRONIC = Electronic.ELECTRONIC;

    /**
     * The table <code>tivicc.mechanic</code>.
     */
    public static final Mechanic MECHANIC = Mechanic.MECHANIC;

    /**
     * The table <code>tivicc.price</code>.
     */
    public static final Price PRICE = Price.PRICE;
}
