/*
 * This file is generated by jOOQ.
 */
package de.tichawa.cis.config.model;


import de.tichawa.cis.config.model.tables.*;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tivicc extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>tivicc</code>
     */
    public static final Tivicc TIVICC = new Tivicc();

    /**
     * The table <code>tivicc.electronic</code>.
     */
    public final Electronic ELECTRONIC = Electronic.ELECTRONIC;

    /**
     * The table <code>tivicc.mechanic</code>.
     */
    public final Mechanic MECHANIC = Mechanic.MECHANIC;

    /**
     * The table <code>tivicc.mechanic</code>.
     */
    public final Equipment EQUIPMENT = Equipment.EQUIPMENT;

    /**
     * The table <code>tivicc.price</code>.
     */
    public final Price PRICE = Price.PRICE;

    /**
     * No further instances allowed
     */
    private Tivicc() {
        super("tivicc", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Electronic.ELECTRONIC,
            Mechanic.MECHANIC,
            Equipment.EQUIPMENT,
            Price.PRICE);
    }
}
